"""
Django settings for OneHeroRush project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from celery.schedules import crontab
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    print(f"BASE_DIR - {BASE_DIR}")
    raise ValueError("SECRET_KEY не найден! Укажи его в .env.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get("DB_NAME"),          
        'USER': os.environ.get("DB_USER"),      
        'PASSWORD': os.environ.get("DB_PASSWORD"), 
        'HOST': os.environ.get("DB_HOST"),     
        'PORT': os.environ.get("DB_PORT"),         
    }
}
print(DATABASES['default']['HOST'])
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    "channels",
    'Users',
    "Characters",
    "Progress",
    "inventory",
    "Quests",
    "Clans",
    "Chats",
    "Leaderboard",
    "Pets",
    "News",
    "Soul",
    "Shop",
    "Messages"

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'



REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = os.environ.get('REDIS_PORT', 6379)
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', '')  # Set in env for security
REDIS_DB_CACHE = 0  # DB 0 для cache
REDIS_DB_CELERY = 1  # DB 1 для Celery broker/results (separate для isolation, avoid flushall impact)
REDIS_DB_CHANNELS = 2  # DB 2 для Channels (WS чат/почта notifications о квестах/достижениях)

# Cache backend: RedisCache с pool для 10k+ conn, decode_responses=True для strings (JSONB stats in characters/items randomized vampirism/crit/evasion x rarity 0.5-3.1)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',  # Используем django_redis вместо django.core.cache
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CACHE}',
        'OPTIONS': {
            'PASSWORD': REDIS_PASSWORD,  # Исправлено на PASSWORD
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {'max_connections': 100, 'retry_on_timeout': True},
            'SOCKET_TIMEOUT': 5,
            'SOCKET_CONNECT_TIMEOUT': 5,
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': 'oneherorush_cache',
        'TIMEOUT': 300,
    },
}

# Celery настройка: broker/result в Redis для async tasks (offline-farm, MMR recalc sum waves/achievements/power для clan rank max_members=30+, notify mail о "150 waves in Hell" + rewards, summon souls lvl up per summon с шанс legendary + unique props +15% spell dmg по Shadow Demon’s Shadow). Актуально: Celery 5.4+ с redis broker async via aioredis.
CELERY_BROKER_URL = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CELERY}'
CELERY_RESULT_BACKEND = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CELERY}'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'UTC'  # Sync with Postgres TZ
CELERY_BROKER_POOL_LIMIT = 100  # Pool для scalability, prevent exhaustion on 10k+ tasks (e.g. bulk chest open 1-20x auto)
CELERY_WORKER_CONCURRENCY = os.cpu_count() or 4  # Auto-scale workers
CELERY_TASK_ACKS_LATE = True  # Retry on failure for critical (e.g. progress save act/etap/wave, inventory items equip/sell for gold/exp)

CELERY_BEAT_SCHEDULE = {
    'reset_daily_quests': {
        'task': 'Quests.tasks.reset_daily_quests',
        'schedule': crontab(hour=0, minute=0),  # Ежедневно в полночь
    },
}

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [(REDIS_HOST, REDIS_PORT)],
#             "password": REDIS_PASSWORD,
#         },
#     },
# }

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]






LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {funcName}:{lineno} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'characters_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/characters.log', 
            'formatter': 'verbose',
        },
        'chats_file': {
            'level': 'INFO', 
            'class': 'logging.FileHandler',
            'filename': 'logs/chats.log',
            'formatter': 'verbose',
        },
        'clans_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler', 
            'filename': 'logs/clans.log',
            'formatter': 'verbose',
        },
        'inventory_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/inventory.log',
            'formatter': 'verbose',
        },
        'leaderboard_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/leaderboard.log',
            'formatter': 'verbose',
        },
        'messages_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/messages.log',
            'formatter': 'verbose',
        },
        'mail_system_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/mail_system.log',
            'formatter': 'verbose',
        },
        'users_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/users.log',
            'formatter': 'verbose',
        },

        'pets_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/pets.log',
            'formatter': 'verbose',
        },
        'quests_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/quests.log',
            'formatter': 'verbose',
        },
        
        'progress_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/progress.log',
            'formatter': 'verbose',
        },
        'soul_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/soul.log',
            'formatter': 'verbose',
        },
        'common_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/common.log',
            'formatter': 'verbose',
        },
        'celery_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/celery.log',
            'formatter': 'verbose',
        },
        'django_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/django.log',
            'formatter': 'verbose',
        },
    },
    
    'loggers': {
        # Кастомные приложения
        'characters': {
            'handlers': ['console', 'characters_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'chats': {
            'handlers': ['console', 'chats_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'clans': {
            'handlers': ['console', 'clans_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'inventory': {
            'handlers': ['console', 'inventory_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'leaderboard': {
            'handlers': ['console', 'leaderboard_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'messages': {
            'handlers': ['console', 'messages_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'mail_system': {
            'handlers': ['console', 'mail_system_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'pets': {
            'handlers': ['console', 'pets_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'quests': {
            'handlers': ['console', 'quests_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console', 'users_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'progress': {
            'handlers': ['console', 'progress_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'soul': {
            'handlers': ['console', 'soul_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'common': {
            'handlers': ['console', 'common_file'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Системные логгеры
        'celery': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'django_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Корневой логгер (ловит все необработанные логи)
        '': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}


WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Добавьте эти настройки:
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Для сбора статики в продакшене
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Дополнительные папки со статикой
]


if DEBUG:
    
    # Middleware для статики
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#drf
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication', 
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle', 
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/min',  
        'user': '100/hour',
    },
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', 
    ],
    'DEFAULT_EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

AUTH_USER_MODEL = "Users.User"

