"""
Django settings for OneHeroRush project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get("DB_NAME"),          
        'USER': os.environ.get("DB_USER"),      
        'PASSWORD': os.environ.get("DB_PASSWORD"), 
        'HOST': os.environ.get("DB_HOST"),     
        'PORT': os.environ.get("DB_PORT"),         
    }
}
print(DATABASES['default']['HOST'])
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    'Users',
    "Characters",
    "Progress",
    "inventory"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'



REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = os.environ.get('REDIS_PORT', 6379)
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', '')  # Set in env for security
REDIS_DB_CACHE = 0  # DB 0 для cache
REDIS_DB_CELERY = 1  # DB 1 для Celery broker/results (separate для isolation, avoid flushall impact)
REDIS_DB_CHANNELS = 2  # DB 2 для Channels (WS чат/почта notifications о квестах/достижениях)

# Cache backend: RedisCache с pool для 10k+ conn, decode_responses=True для strings (JSONB stats in characters/items randomized vampirism/crit/evasion x rarity 0.5-3.1)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CACHE}',
        'OPTIONS': {
            'PASSWORD': REDIS_PASSWORD,
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',  # django-redis 5.4+ для sentinel support
            'CONNECTION_POOL_KWARGS': {'max_connections': 100, 'retry_on_timeout': True},  # Pool для perf, retry для resilience
            'SOCKET_TIMEOUT': 5,  # Sec, prevent hangs on high load (spike перед рулеткой/кейсами за 6-12 souls/keys/diamonds)
            'SOCKET_CONNECT_TIMEOUT': 5,
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',  # Compress для bandwidth save on large serializers (e.g. souls open/hidden stats JSONB для баланса патчей)
            'IGNORE_EXCEPTIONS': True,  # Graceful fallback to no-cache on Redis down, log via sentry
        },
        'KEY_PREFIX': 'oneherorush_cache',  # Namespace для multi-tenant if needed
        'TIMEOUT': 300,  # Default ttl=5min для dynamic data (e.g. progress act/wave/location, offline-farm Celery calc +gold/keys с bonus online > offline)
    },
}

# Celery настройка: broker/result в Redis для async tasks (offline-farm, MMR recalc sum waves/achievements/power для clan rank max_members=30+, notify mail о "150 waves in Hell" + rewards, summon souls lvl up per summon с шанс legendary + unique props +15% spell dmg по Shadow Demon’s Shadow). Актуально: Celery 5.4+ с redis broker async via aioredis.
CELERY_BROKER_URL = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CELERY}'
CELERY_RESULT_BACKEND = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CELERY}'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'UTC'  # Sync with Postgres TZ
CELERY_BROKER_POOL_LIMIT = 100  # Pool для scalability, prevent exhaustion on 10k+ tasks (e.g. bulk chest open 1-20x auto)
CELERY_WORKER_CONCURRENCY = os.cpu_count() or 4  # Auto-scale workers
CELERY_TASK_ACKS_LATE = True  # Retry on failure for critical (e.g. progress save act/etap/wave, inventory items equip/sell for gold/exp)



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#drf
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication', 
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle', 
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/min',  
        'user': '100/hour',
    },
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', 
    ],
    'DEFAULT_EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
}

AUTH_USER_MODEL = "Users.User"

