# Generated by Django 5.2.6 on 2025-09-22 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(choices=[('Pudge', 'Pudge'), ('Necrophos', 'Necrophos'), ('Juggernaut', 'Juggernaut'), ('Phantom Assassin', 'Phantom Assassin'), ('Lifestealer', 'Lifestealer'), ('Rubick', 'Rubick'), ('Ursa', 'Ursa'), ('Axe', 'Axe'), ('Shadow Fiend', 'Shadow Fiend'), ('Zeus', 'Zeus'), ('Lion', 'Lion'), ('Legion Commander', 'Legion Commander'), ('Sniper', 'Sniper'), ('Invoker', 'Invoker'), ('Crystal Maiden', 'Crystal Maiden'), ('Windranger', 'Windranger'), ('Ogre Magi', 'Ogre Magi'), ('Witch Doctor', 'Witch Doctor'), ('Drow Ranger', 'Drow Ranger'), ('Vengeful Spirit', 'Vengeful Spirit'), ('Lich', 'Lich'), ('Tidehunter', 'Tidehunter'), ('Slark', 'Slark'), ('Mirana', 'Mirana'), ('Bounty Hunter', 'Bounty Hunter'), ('Riki', 'Riki'), ('Spirit Breaker', 'Spirit Breaker')], max_length=50)),
                ('level', models.PositiveIntegerField(default=1)),
                ('stats', models.JSONField(default=dict)),
                ('race_bonus', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'hero_name'], name='Characters__user_id_997f55_idx'), models.Index(fields=['user', 'is_active'], name='Characters__user_id_0c7cab_idx')],
                'unique_together': {('user', 'hero_name')},
            },
        ),
    ]
