# Generated by Django 5.2.6 on 2025-10-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='characters', to='inventory.item'),
        ),
    ]
