# Generated by Django 5.2.6 on 2025-10-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0002_character_items'),
        ('Soul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='soul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_souls', to='Soul.soul'),
        ),
    ]
