# Generated by Django 5.2.6 on 2025-10-05 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Characters', '0002_character_items'),
        ('Users', '0005_user_soul_coupons_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummonLevel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience', models.PositiveBigIntegerField(default=0)),
                ('rarity_chances', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Soul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(choices=[('COMMON', 'Обычный'), ('SUPERIOR', 'Превосходный'), ('EXCELLENT', 'Отличный'), ('RARE', 'Редкий'), ('UNIQUE', 'Уникальный'), ('EPIC', 'Эпический'), ('LEGENDARY', 'Легендарный'), ('IMMORTAL', 'Бессмертие')], default='COMMON', max_length=20)),
                ('open_stats', models.JSONField(default=dict)),
                ('hidden_stats', models.JSONField(default=dict)),
                ('unique_properties', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=100))),
                ('level', models.PositiveIntegerField(default=1)),
                ('multiplier', models.FloatField(default=0.5)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souls', to='Characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSoul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summon_count', models.PositiveIntegerField(default=0)),
                ('equipped_to_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_souls', to='Characters.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_souls', to=settings.AUTH_USER_MODEL)),
                ('soul', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Soul.soul')),
            ],
        ),
        migrations.AddIndex(
            model_name='soul',
            index=models.Index(fields=['character', 'rarity'], name='Soul_soul_charact_4cb913_idx'),
        ),
        migrations.AddConstraint(
            model_name='soul',
            constraint=models.UniqueConstraint(fields=('character',), name='unique_soul_per_character_template'),
        ),
        migrations.AddIndex(
            model_name='playersoul',
            index=models.Index(fields=['user', 'equipped_to_character'], name='Soul_player_user_id_733fea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playersoul',
            unique_together={('user', 'equipped_to_character')},
        ),
    ]
