# Generated by Django 5.2.6 on 2025-10-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soul',
            name='unique_properties',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
