# Generated by Django 5.2.6 on 2025-10-05 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rarity', models.CharField(choices=[('COMMON', 'Обычный'), ('SUPERIOR', 'Превосходный'), ('EXCELLENT', 'Отличный'), ('RARE', 'Редкий'), ('UNIQUE', 'Уникальный'), ('EPIC', 'Эпический'), ('LEGENDARY', 'Легендарный'), ('IMMORTAL', 'Бессмертие')], default='COMMON', max_length=20)),
                ('extra_bonus', models.JSONField(blank=True, default=dict)),
                ('bonus_gold', models.FloatField(default=0)),
                ('bonus_mana_regen', models.FloatField(default=0)),
                ('bonus_spell_damage', models.FloatField(default=0)),
                ('bonus_magic_resist', models.FloatField(default=0)),
                ('bonus_health', models.IntegerField(default=0)),
                ('bonus_hp_regen', models.FloatField(default=0)),
                ('bonus_damage', models.FloatField(default=0)),
                ('bonus_move_speed', models.FloatField(default=0)),
                ('bonus_attack_range', models.FloatField(default=0)),
                ('bonus_crit_chance', models.FloatField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['rarity'], name='Pets_pet_rarity_2d8eb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSummonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summon_level', models.PositiveIntegerField(default=1)),
                ('summon_exp', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summon_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('level', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_selected'], name='Pets_userpe_user_id_45be68_idx')],
                'unique_together': {('user', 'pet')},
            },
        ),
    ]
