# Generated by Django 5.2.6 on 2025-10-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
