# Generated by Django 5.2.6 on 2025-09-29 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'level'], name='inventory_c_user_id_4a1070_idx')],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Power Treads', 'Power Treads'), ('Phase Boots', 'Phase Boots'), ('Tranquil Boots', 'Tranquil Boots'), ('Arcane Boots', 'Arcane Boots'), ('Guardian Greaves', 'Guardian Greaves'), ('Boots of Travel', 'Boots of Travel'), ('Hand of Midas', 'Hand of Midas'), ('Manta Style', 'Manta Style'), ('Blink Dagger', 'Blink Dagger'), ('Shadow Blade', 'Shadow Blade'), ('Silver Edge', 'Silver Edge'), ('Monkey King Bar', 'Monkey King Bar'), ('Battle Fury', 'Battle Fury'), ('Crystalys', 'Crystalys'), ('Daedalus', 'Daedalus'), ('Abyssal Blade', 'Abyssal Blade'), ('Magic Wand', 'Magic Wand'), ('Null Talisman', 'Null Talisman'), ('Wraith Band', 'Wraith Band'), ('Bracer', 'Bracer'), ('Ring of Basilius', 'Ring of Basilius'), ('Medallion of Courage', 'Medallion of Courage'), ('Solar Crest', 'Solar Crest'), ('Dragon Lance', 'Dragon Lance'), ('Dagon', 'Dagon'), ('Orchid Malevolence', 'Orchid Malevolence'), ('Bloodthorn', 'Bloodthorn'), ('Scythe of Vyse', 'Scythe of Vyse'), ("Shiva's Guard", "Shiva's Guard"), ('Rod of Atos', 'Rod of Atos'), ('Glimmer Cape', 'Glimmer Cape'), ('Force Staff', 'Force Staff'), ('Mekansm', 'Mekansm'), ('Pipe of Insight', 'Pipe of Insight'), ('Urn of Shadows', 'Urn of Shadows'), ('Spirit Vessel', 'Spirit Vessel'), ('Lotus Orb', 'Lotus Orb'), ('Aether Lens', 'Aether Lens'), ('Vanguard', 'Vanguard'), ('Crimson Guard', 'Crimson Guard'), ('Hood of Defiance', 'Hood of Defiance'), ('Black King Bar', 'Black King Bar'), ('Assault Cuirass', 'Assault Cuirass'), ('Heart of Tarrasque', 'Heart of Tarrasque'), ('Blade Mail', 'Blade Mail'), ('Desolator', 'Desolator'), ('Maelstrom', 'Maelstrom'), ('Mjollnir', 'Mjollnir'), ('Armlet of Mordiggian', 'Armlet of Mordiggian'), ('Sange and Yasha', 'Sange and Yasha'), ("Heaven's Halberd", "Heaven's Halberd"), ('Skull Basher', 'Skull Basher'), ('Echo Sabre', 'Echo Sabre'), ('Claymore', 'Claymore'), ('Broadsword', 'Broadsword'), ('Mithril Hammer', 'Mithril Hammer'), ('Javelin', 'Javelin'), ('Blood Grenade', 'Blood Grenade'), ('Gauntlets of Strength', 'Gauntlets of Strength'), ('Mantle of Intelligence', 'Mantle of Intelligence'), ('Slippers of Agility', 'Slippers of Agility'), ('Circlet', 'Circlet')], max_length=50)),
                ('level', models.PositiveIntegerField(default=1)),
                ('stats', models.JSONField(default=dict)),
                ('rarity_multiplier', models.FloatField(choices=[(0.5, 'Common'), (1.0, 'Uncommon'), (1.5, 'Rare'), (2.0, 'Mythical'), (2.5, 'Legendary'), (2.8, 'Ancient'), (3.0, 'Immortal'), (3.1, 'Arcana')], default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'name'], name='inventory_i_user_id_0c6c5f_idx')],
            },
        ),
    ]
