# Generated by Django 5.2.6 on 2025-10-11 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['user', '-created_at'], name='Messages_me_user_id_6c15fc_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['user', 'is_read'], name='Messages_me_user_id_3db65f_idx'),
        ),
    ]
