# Generated by Django 5.2.3 on 2025-09-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AddField(
            model_name="user",
            name="nik",
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
