# Generated by Django 5.2.3 on 2025-09-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_remove_user_email_user_nik"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="nik",
        ),
    ]
