# Generated by Django 5.2.6 on 2025-09-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_user_nik'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_heroes',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='mmr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='purchased_heroes',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['max_heroes'], name='Users_user_max_her_d2b74e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['mmr'], name='Users_user_mmr_ea5150_idx'),
        ),
    ]
