# Generated by Django 5.2.6 on 2025-10-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_user_soul_coupons_userprofile'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='Users_user_max_her_d2b74e_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='Users_user_usernam_e616bd_idx'),
        ),
    ]
