# Generated by Django 5.2.6 on 2025-10-05 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtask',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='News.mailtemplate'),
        ),
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
