# Generated by Django 5.2.6 on 2025-10-11 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_mailtask_template_delete_mail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailtask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mailtask',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mailtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('done', 'Завершена'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='mailtask',
            index=models.Index(fields=['status', 'created_at'], name='News_mailta_status_8ae9d8_idx'),
        ),
        migrations.AddIndex(
            model_name='mailtemplate',
            index=models.Index(fields=['name'], name='News_mailte_name_40729c_idx'),
        ),
    ]
