# Generated by Django 5.2.6 on 2025-10-09 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clans', '0001_initial'),
        ('Leaderboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clanleaderboardentry',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='heroleaderboardentry',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clanleaderboardentry',
            name='points',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='heroleaderboardentry',
            name='hero_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='heroleaderboardentry',
            name='power',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='mmr',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='clanleaderboardentry',
            index=models.Index(fields=['-points'], name='Leaderboard_points_05162a_idx'),
        ),
        migrations.AddIndex(
            model_name='heroleaderboardentry',
            index=models.Index(fields=['hero_name', '-power'], name='Leaderboard_hero_na_862f39_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['-mmr', 'user'], name='Leaderboard_mmr_9d5867_idx'),
        ),
    ]
