# Generated by Django 5.2.6 on 2025-09-23 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('heaven', 'Рай'), ('god_heaven', 'Рай с богом'), ('purgatory', 'Чистилище'), ('hell', 'Ад'), ('devil_hell', 'Ледяное Озеро Коцит')], default='hell', max_length=20)),
                ('act', models.IntegerField(default=1)),
                ('stage', models.IntegerField(default=1)),
                ('wave', models.IntegerField(default=1)),
                ('waves_completed', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('normal', 'Нормальный'), ('hard', 'Сложный'), ('insane', 'Нереальный')], default='easy', max_length=20)),
                ('last_online', models.DateTimeField(default=django.utils.timezone.now)),
                ('offline_gold', models.IntegerField(default=0)),
                ('offline_keys', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='Progress_pr_user_id_99f23d_idx')],
            },
        ),
    ]
